
version: "3.9"

services:
  pgvector:
    image: pgvector/pgvector:pg16
    container_name: pgvector_rag
    environment:
      POSTGRES_USER: "your_username"
      POSTGRES_PASSWORD: "your_password"
      POSTGRES_DB: ragdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata_rag:/var/lib/postgresql/data

volumes:
  pgdata_rag:
